language: php
php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

before_script:
  # Install Drush
  - pyrus channel-discover pear.drush.org
  - pyrus install drush/drush
  - phpenv rehash
  # Prepare db and stub sendmail path with true to prevent delivery errors
  - mysql -e 'create database drupal'
  - echo 'sendmail_path = "/bin/true"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Install site with hotsauce distro
  - drush si hotsauce --db-url=mysql://root:@localhost/drupal --yes
  - drush en --yes simpletest
  - drush cc all
  # Setup test webserver
  - drush runserver --server=builtin 8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done
  # Set simpletest to non-verbose
  - drush vset --yes simpletest_verbose FALSE

script: drush test-run Syslog --xml --uri=http://127.0.0.1:8080

matrix:
  allow_failures:
    - drush
    - drush si hotsauce --db-url=mysql://root:@localhost/drupal --yes